// This file was generated by github.com/nelsam/hel.  Do not
// edit this code by hand unless you *really* know what you're
// doing.  Expect any changes made manually to be overwritten
// the next time hel regenerates this file.

package diff_test

type mockSprinter struct {
	SprintCalled chan bool
	SprintInput  struct {
		Arg0 chan []interface{}
	}
	SprintOutput struct {
		Ret0 chan string
	}
}

func newMockSprinter() *mockSprinter {
	m := &mockSprinter{}
	m.SprintCalled = make(chan bool, 100)
	m.SprintInput.Arg0 = make(chan []interface{}, 100)
	m.SprintOutput.Ret0 = make(chan string, 100)
	return m
}
func (m *mockSprinter) Sprint(arg0 ...interface{}) string {
	m.SprintCalled <- true
	m.SprintInput.Arg0 <- arg0
	return <-m.SprintOutput.Ret0
}
